name: "SolarSynkV3"
description: "Home Assistant add-on for syncing solar/inverter data from SynSynk.net"
version: "3.0.18"
slug: "solar_synkv3"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/martinville/solarsynkv3/tree/main"
homeassistant_api: true
  
  
options:
  sunsynk_user: ""
  sunsynk_pass: ""
  sunsynk_serial: ""
  Refresh_rate: 300
  data_source: "sunsynk"
  
schema:
  sunsynk_user: str
  sunsynk_pass: password
  sunsynk_serial: str
  Refresh_rate: int
  data_source: "list(sunsync|generic)"
